#!/bin/bash

if [ "$1" == "k8s" ]; then
    echo "create sbox in k8s"
    EXEC_KUBECTL=$(which kubectl)
    if [ -n $EXEC_KUBECTL ]; then
        eval "sudo $EXEC_KUBECTL run --rm -it sbox --image=hm.grepcode.cn:55582/basic/sbox:0.1 --restart=Never"
    fi
    echo "exit sbox in k8s"
    exit 0
fi

if [ "$1" == "docker" ]; then
    echo "create sbox in docker"
    sudo docker run --rm -it hm.grepcode.cn:55582/basic/sbox:0.1
    echo "exit sbox in docker"
    exit 0
fi
